// This file has been generated by go-spector; DO NOT EDIT.
package router

import (
	"github.com/go-chi/chi"
	"net/http"
)

func New(getFn http.HandlerFunc, addFn http.HandlerFunc) func(r chi.Router) {
	return func(r chi.Router) {
		r.Method(http.MethodPost, "/customer/{id}", NewGetHandler(getFn))
		r.Method(http.MethodGet, "/customer", NewAddHandler(addFn))
	}
}

func NewWithMiddleware(
	getFn http.HandlerFunc,
	addFn http.HandlerFunc,
	middlewares chi.Middlewares,
) chi.Router {
	var r chi.Router
	r = chi.NewRouter()
	r = r.With(middlewares...)
	r.Get("/todos/{id}", NewGetHandler(getFn).ServeHTTP)
	r.Post("/todos", NewAddHandler(addFn).ServeHTTP)

	return r
}
